### ISSUE TITLE
Plugin implementation

### ISSUE THREAD

**Issue by 0x52a1** [0x52a1/hackircd#11]
This will close #5 (changes are being pushed to `latest` as they happen)

# TODO: 

* [x] Rip out all existing client code
* [ ] Add plugin config block support
* [ ] Add code to start plugin executables
* [ ] Send plugin event `init` with config block
* [ ] Store list of plugin-handled commands and events
* [ ] Pipe incoming events to plugins registered to handle those events
* [ ] Pipe some test events (probably a ping) into plugins to test handling
* [ ] Hook up code in `client.go` to plugin interface
   * [ ] L99: Client.SetNick (event `_user_update`)
   * [ ] L115: Client.FinishRegistration (event `_user_connect`)
   * [ ] L125: Client.Close (event `_user_disconnect`)
   * [ ] L250: Client.Handle (event `_command`)
* [ ] Update server state on incoming `_user_update` and `_user_disconnect` events
* ??? (to be updated)
